{% set name = "pylops" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbe8ab8d333c75fc04d3241bbdbb1f98612b7149fa47ebc9de124e5cb626730a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py2k]

requirements:
  build:
      - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools_scm 
    - pytest-runner
  run:
    - python
    - pip
    - llvmlite
    - numba
    - pyfftw
    - pywavelets
    - scikit-fmm
    - scipy

test:
  imports:
    - pylops
  commands:
    - pip check

about:
  home: https://github.com/equinor/pylops
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'PyLops – A Linear-Operator Library for Python'
  description: |
    Python library implementing linear operators to allow solving large-scale optimization
    problems without requiring to explicitly create a dense (or sparse) matrix.
  doc_url: https://pylops.readthedocs.io
  dev_url: https://github.com/equinor/pylops

extra:
  recipe-maintainers:
    - jan-janssen
    - mrava87
