{% set name = "pylops" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 121d3456047015c0d193328048099c13423802aa665593e1002c80813f04a379

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools_scm
    - pytest-runner
  run:
    - python
    - pip
    - llvmlite
    - numba
    - pyfftw
    - pywavelets
    - scikit-fmm
    - scipy

test:
  imports:
    - pylops
  commands:
    - pip check

about:
  home: https://github.com/equinor/pylops
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: PyLops – A Linear-Operator Library for Python
  description: |
    Python library implementing linear operators to allow solving large-scale optimization
    problems without requiring to explicitly create a dense (or sparse) matrix.
  doc_url: https://pylops.readthedocs.io
  dev_url: https://github.com/equinor/pylops

extra:
  recipe-maintainers:
    - jan-janssen
    - mrava87
