{% set name = "pylops" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9460fd2d147070cb508267a2a9ce11037c87e472e7ddb85d81c4d12f83ca282

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win]

requirements:
  build:
      - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - llvmlite
    - numba
    - pyfftw
    - scikit-fmm
    - scipy

test:
  imports:
    - pylops

about:
  home: https://github.com/equinor/pylops
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'PyLops – A Linear-Operator Library for Python'
  description: |
    This Python library is inspired by the MATLAB Spot – A Linear-Operator Toolbox project.

    Linear operators and inverse problems are at the core of many of the most used algorithms in signal processing,
    image processing, and remote sensing. When dealing with small-scale problems, the Python numerical scientific
    libraries numpy and scipy allow to perform many of the underlying matrix operations (e.g., computation of
    matrix-vector products and manipulation of matrices) in a simple and compact way.
  doc_url: https://pylops.readthedocs.io
  dev_url: https://github.com/equinor/pylops

extra:
  recipe-maintainers:
    - jan-janssen
    - mrava87
