schema_version: 1

context:
  name: pylops
  version: "2.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pylops-${{ version }}.tar.gz
  sha256: 7fb6a3e4c57f14059131aded722ae9c331c12f26075d7e7e98e4ec3915e1262c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.21.0
    - scipy >=1.11.0

tests:
  - python:
      imports:
        - pylops
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: PyLops – A Linear-Operator Library for Python
  description: |
    Python library implementing linear operators to allow solving large-scale optimization
    problems without requiring to explicitly create a dense (or sparse) matrix.
  homepage: https://github.com/PyLops/pylops
  repository: https://github.com/PyLops/pylops
  documentation: https://pylops.readthedocs.io

extra:
  recipe-maintainers:
    - jan-janssen
    - mrava87
