travis:
  secure:
    BINSTAR_TOKEN: eaZeR/87FlwmoxIAwRbOHNqE1W/cV5N8FIF+Ry2dpyJ/p/Zn6z67CkQehiD91u+Tvzc4DvgMHUZ2pwvbZuU5GycVmsgLftl2Wnn9Dtj2dZQdh88tI+/90y7GI73WHR9Dzm0iHqBHvoU+1uZWELH+2zaTJ5rWy48Cy44j/mOxg7Vy4meMwQsJvaGG1CsVQC37UvePlEsApMBtLrl3SG2YgDf/QcZhYGhhi6oukKR/GT8xMlcvItIMkRXe2eQ9LexQbngzSonyzTHdWP4bFwvdw8xCH0PBAxUe/jcCnZvL292iJErrwQH8y4TLsKJRrr9DyVcehdOLq3BtcEX47gTfKqyYGF/6/Wl2BNEIA/c26beGcPSqUFw4QmkmQ8Tpmo0TFWR4onwes65tkFuNf4wVn/9LskTZ5X626wMkT4Vw+ZINjMQvjcICYdoR2YXrB6C6c+2nnBpOSaQD+yKiKKrghK9Q8Sdbt0n6qrm+itDgLah8uzf9eUgsZey5MhUHJDKf8onNrgOEjGrAnwNw6dsMDWFKiwdmKKLjiONzMyebdPX0L36ATyj9ym6LaY5ztKesw3w5+LzLvxuTlDgmz8uhkG4I1Nd8kYfQXfl4bmwhHGiGlG6pq/nrNv/nfKdtevqhWyMoDRr6XjKGNXZYAgDBZWPKKiFHsxYldPdKsIv0MUA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
